/**
 * Static data loaders for pre-computed dashboard JSONs.
 * All data is generated by scripts/extract_data.py from the source parquet.
 */

const DATA_BASE = '/data';

async function loadJson<T>(filename: string): Promise<T> {
  const res = await fetch(`${DATA_BASE}/${filename}`);
  if (!res.ok) throw new Error(`Failed to load ${filename}: ${res.status}`);
  return res.json();
}

// --- Summary (Tab 1) ---
export interface SummaryKPIs {
  totalTrips: number;
  uniqueDays: number;
  operators: number;
  totalIncome: number;
  avgDailyTrips: number;
  avgMiles: number;
  avgTimeMin: number;
}

export interface SummaryData {
  kpis: SummaryKPIs;
  byHour: Array<{ pickup_hour: number; operator: string; trips: number }>;
  byWeekday: Array<{ day_name: string; operator: string; trips: number }>;
  heatmap: Array<[number, number, number]>; // [x, y, value]
  dailyTrend: Array<{ pickup_date: string; operator: string; trips: number }>;
  operatorSummary: Array<{
    operator: string;
    trips: number;
    income: number;
    tips: number;
    tip_avg: number;
    tip_pct: number;
    avg_miles: number;
    avg_time_min: number;
  }>;
  boroughDistribution: Array<{ pickup_borough: string; trips: number }>;
}

export const loadSummary = () => loadJson<SummaryData>('summary.json');

// --- Peak Hours (Tab 2) ---
export interface PeakHoursData {
  byHourOperator: Array<{ pickup_hour: number; operator: string; trips: number }>;
  byWeekdayOperator: Array<{ day_name: string; operator: string; trips: number }>;
  topZonesOperator: Array<{ pickup_zone: string; operator: string; trips: number }>;
  hotspots: Array<[number, number, number]>;
  topZoneNames: string[];
}

export const loadPeakHours = () => loadJson<PeakHoursData>('peak_hours.json');

// --- Maps (Tab 3) ---
export interface ZoneFeature {
  zone: string;
  borough: string;
  trips: number;
  lat: number;
  lon: number;
}

export interface FlowData {
  pickup_zone: string;
  dropoff_zone: string;
  trip_count: number;
}

export interface MapsData {
  zoneFeatures: ZoneFeature[];
  flows: FlowData[];
  flowZones: string[];
}

export const loadMaps = () => loadJson<MapsData>('maps.json');

// --- Uber vs Lyft (Tab 4) ---
export interface UberLyftData {
  hasData: boolean;
  tripDistribution: Record<string, number>;
  incomeDistribution: Record<string, number>;
  metrics: Record<string, {
    trips: number;
    avgFare: number;
    avgTip: number;
    avgMiles: number;
    avgTimeMin: number;
    pricePerMile: number;
    pricePerMinute: number;
  }>;
  tipAnalysis: Record<string, {
    avgTip: number;
    pctTripsWithTip: number;
    tipPctOfIncome: number;
  }>;
  tipHistogram: Array<{ tip_pct_bucket: number; operator: string; count: number }>;
  topZonesOperator: Array<{ pickup_zone: string; operator: string; trips: number }>;
  marketHeatmap: Array<{ zone: string; operator: string; pct: number }>;
  hourly: Array<{ pickup_hour: number; operator: string; trips: number }>;
  marketHourly: Array<{ hour: number; operator: string; pct: number }>;
  daily: Array<{ day_name: string; operator: string; trips: number }>;
  airport: Record<string, {
    byOperator: Record<string, number>;
    total: number;
  }>;
}

export const loadUberVsLyft = () => loadJson<UberLyftData>('uber_vs_lyft.json');

// --- Income (Tab 5) ---
export interface IncomeData {
  totals: Record<string, number>;
  composition: Array<{ name: string; value: number }>;
  byCompany: Array<Record<string, string | number>>;
  dailyTrend: Array<{ date: string; operator: string; income: number }>;
  scatter: Array<{ driver_pay: number; tips: number; operator: string }>;
  tipHistogram: Array<{ bucket: number; operator: string; count: number }>;
}

export const loadIncome = () => loadJson<IncomeData>('income.json');

// --- Airports (Tab 6) ---
export interface AirportKPIs {
  toAirport: number;
  fromAirport: number;
  totalAirport: number;
  toPct: number;
  fromPct: number;
  totalPct: number;
  avgFare: number;
}

export interface AirportDirection {
  count: number;
  avgMiles?: number;
  avgMilesDelta?: number;
  avgFare?: number;
  avgFareDelta?: number;
  byOperator?: Record<string, number>;
  hourly?: Array<{ pickup_hour: number; trips: number; pct: number }>;
  airportDistribution?: Array<{ airport: string; trips: number; pct: number }>;
}

export interface AirportsData {
  kpis: AirportKPIs;
  toAirport: AirportDirection;
  fromAirport: AirportDirection;
  weeklyTrend: Array<{ day_name: string; to_trips: number; from_trips: number }>;
  fareComparison: Record<string, {
    min: number;
    q1: number;
    median: number;
    q3: number;
    max: number;
    mean: number;
  }>;
}

export const loadAirports = () => loadJson<AirportsData>('airports.json');

// --- ML Mock (Tab 7) ---
export interface MlMockData {
  models: Array<{ name: string; type: string; performance: number }>;
  featureImportance: Array<{ feature: string; importance: number }>;
  samplePrediction: {
    input: Record<string, string | number>;
    predicted_fare: number;
    confidence: number;
  };
}

export const loadMlMock = () => loadJson<MlMockData>('ml_mock.json');
